models:  
  - name: chatgpt
    provider: openai
    model: gpt-4.1

  - name: gemini-2.5-flash
    provider: gemini
    model: gemini-2.5-flash-preview-04-17

  - name: perplexity-sonar
    provider: perplexity
    model: sonar

  - name: deepseekv3
    provider: openrouter
    model: deepseek/deepseek-chat-v3-0324:free

  - name: claude
    provider: anthropic
    model: claude-3-5-haiku-20241022

  - name: grok-3
    provider: grok
    model: grok-3

  